# This is a basic workflow run terraform codes to create instances in AWS

name: Terra CI/CD

on:
  push:
    branches: 
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Estimate AWS Cost
        run: infracost breakdown --path=. --format=json

    
      - name: Run Terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          policy_type: 'aws'
          only_warn: true
          sarif_upload: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          

      - name: Terraform Destroy
        run: terraform destroy -auto-approve